[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Brabant digital twin energy system"
authors = [{name = "Naud Loomans", email = "naud@zenmo.com"}]
dynamic = ["version", "description"]
